### ISSUE TITLE
Other Datasets

### ISSUE THREAD

**Issue by barnes88** [cgtuebingen/ggnn#10]
Hello,

I was wondering if you could provide a link to the other datasets used in the paper (specifically GloVe, NYTimes, deep1B). They don't seem to exist in the [texmex corpus](http://corpus-texmex.irisa.fr/). Are there scripts you used to preprocess the data from other sources?

**Comment by LukasRuppert** [comment]
Yes, I still have them:
https://gist.github.com/LukasRuppert/6f80e283d40eb09b734738772b30bff0

The config shown there is for NYTimes.
For GloVe, you need to change the dimension from 256 to 200.

And there might be nicer ways to do this :)
That was just the fastest way to do it at the time.

Not sure about deep1B, Fabian downloaded that one.
I guess we used this script: https://github.com/arbabenko/GNOIMI/blob/master/downloadDeep1B.py
If they already come in the correct format, the individual chunks only need to be concatenated.
E.g., using `cat base_0 base_1 ... > base`

**Comment by barnes88** [comment]
Thank you for the scripts.
