### ISSUE TITLE
Has this paper been accepted by any conference or journal?

### ISSUE THREAD

**Issue by KinglittleQ** [cgtuebingen/ggnn#4]
Thanks for your great work. I'm very interested in it and noticed that your paper was published at Arxiv in 2019. By now, has this paper been accepted by any conference or journal?

**Comment by LukasRuppert** [comment]
Sadly, the paper has so far not been accepted.
We're currently working on another revision and plan to resubmit end of this month.

**Comment by KinglittleQ** [comment]
Thanks for your reply. Good luck to you!
